# Base configuration
##########################################################
# <<<<<<<<<<<<<<<<< Update the line below when RELEASING a new minor version
baseURL = "https://googlecloudplatform.github.io/kubeflow-gke-docs/dev"
title = "Kubeflow on Google Cloud Platform"
description = "Open-source machine learning platform running on Google Kubernetes Engine"

# Language settings
contentDir = "content/en"
defaultContentLanguage = "en"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

enableRobotsTXT = true
canonifyURLs = true

# Will give values to .Lastmod etc.
enableGitInfo = true

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"
# Relative urls:
# relativeURLs = true

# Deprecated or inactive
ignoreFiles = [
  "content/en/news/*",
]

# Image processing configuration.
[imaging]
  resampleFilter = "CatmullRom"
  quality = 75
  anchor = "smart"

# Configure how URLs look like per section.
[permalinks]
  news = "/:section/:year/:month/:day/:slug/"

##########################################################
# Goldmark markdown parser
##########################################################
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    # See a complete list of available styles at https://xyproto.github.io/splash/docs/all.html
    style = "tango"
    # Uncomment if you want your chosen highlight style used for code blocks without a specified language
    guessSyntax = "true"
    lineNumbersInTable = true
    noClasses = false
    anchorLineNos = false
    codeFences = true
    hl_Lines = ''
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
##########################################################
# Google Analytics
##########################################################
[services]
  [services.googleAnalytics]
    # Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
    id = "G-GK9XL47N6S"
##########################################################
# Hugo module configuration
##########################################################
[module]
  # uncomment line below for temporary local development of module
  # replacements = "github.com/google/docsy -> ../../docsy"
  [module.hugoVersion]
    extended = true
    min = "0.75.0"
  [[module.imports]]
    path = "github.com/google/docsy"
    disable = false
  [[module.imports]]
    path = "github.com/google/docsy/dependencies"
    disable = false    
##########################################################
# Docsy taxonomies
##########################################################
# You can add your own taxonomies
# disableKinds = ["taxonomy", "taxonomyTerm"]
[taxonomies]
  tag = "tags"
  category = "categories"
  [params.taxonomy]
    # set taxonomyCloud = [] to hide taxonomy clouds
    taxonomyCloud = ["tags", "categories"] 
    # If used, must have same length as taxonomyCloud
    taxonomyCloudTitle = ["Tags", "Categories"] 
    # set taxonomyPageHeader = [] to hide taxonomies on the page headers
    taxonomyPageHeader = ["tags", "categories"] 
##########################################################
# Menu header
# Update when RELEASING a new minor version
##########################################################
[menu]
  [[menu.main]]
    name = "Docs"
    weight = -101
    #pre = "<i class='fa-solid fa-books pr-2'></i>"
    url = "docs/"
#  [[menu.main]]
#    name = "News"
#    weight = -100
#    #pre = "<i class='fa-solid fa-rss pr-2'></i>"
#    url = "news/"
  [[menu.main]]
    name = "Manifests"
    weight = -99
    pre = "<i class='fa-brands fa-github pr-2'></i>"
    url = "https://github.com/googlecloudplatform/kubeflow-distribution"
##########################################################
# Language configuration
##########################################################
[languages]
  [languages.en]
    title = "Kubeflow on Google Cloud Platform"
    description = "Open-source machine learning platform running on Google Kubernetes Engine"
    languageName ="English"
    # Weight used for sorting.
    weight = 1
##########################################################
# Site Params
# Update when RELEASING a new minor version
##########################################################
# Comment out if you don't want the "print entire section" link enabled.
[outputs]
  section = ["HTML", "print", "RSS"]

[params]
  copyright = "The Kubeflow Authors."
  privacy_policy = "https://policies.google.com/privacy"

  # First one is picked as the Twitter card image if not set on page.
  # images = ["images/project-illustration.png"]

  # Menu title if your navbar has a versions selector to access old versions of your site.
  # This menu appears only if you have at least one [params.versions] set.
  # <<<<<<<<<<<<<<<<< Update the line below when RELEASING a new minor version 
  version_menu = "dev"
  # Flag used in the "version-banner" partial to decide whether to display a 
  # banner on every page indicating that this is an archived version of the docs.
  # Set this flag to "true" if you want to display the banner.
  # <<<<<<<<<<<<<<<<< Update the line below when RELEASING a new minor version 
  archived_version = false
  # The version number for the version of the docs represented in this doc set.
  # Used in the "version-banner" partial to display a version number for the 
  # current doc set.
  # <<<<<<<<<<<<<<<<< Update the line below when RELEASING a new minor version 
  version = "dev"
  # URL prefix for this specific version
  # <<<<<<<<<<<<<<<<< Update the line below when RELEASING a new minor version 
  version_url_prefix = "/dev"
  # A link to latest version of the docs. Used in the "version-banner" partial to
  # point people to the main doc site.
  url_latest_version = "https://googlecloudplatform.github.io/kubeflow-gke-docs/docs"
  
  # Repository configuration (URLs for in-page links to opening issues and suggesting changes)
  github_repo = "https://github.com/googlecloudplatform/kubeflow-gke-docs"
  
  # <<<<<<<<<<<<<<<<< Update the line below when RELEASING a new minor version 
  github_branch= "main"
  # github_subdir = "dev"

  # Google Custom Search Engine ID. Remove or comment out to disable search.
  gcs_engine_id = "37be36edbefe142f6"

  # An optional link to a related project repo. For example, the sibling repository where your product code lives.
  github_project_repo = "https://github.com/googlecloudplatform/kubeflow-distribution"

  # Enable Algolia DocSearch
  algolia_docsearch = false

  # Enable Lunr.js offline search
  offlineSearch = false

  # Enable syntax highlighting and copy buttons on code blocks with Prism
  prism_syntax_highlighting = true

  # These entries appear in the drop-down menu at the top of the website.
  [[params.versions]]
    # <<<<<<<<<<<<<<<<< Update the line below when RELEASING a new minor version 
    version = "v1.7 (latest)"
    githubbranch = "v1.7-release"
    url = "https://googlecloudplatform.github.io/kubeflow-gke-docs/docs"
  [[params.versions]]
    version = "v1.6"
    githubbranch = "v1.6-release"
    url = "https://googlecloudplatform.github.io/kubeflow-gke-docs/v1.6/docs"
  [[params.versions]]
    version = "v1.5"
    githubbranch = "v1.5-release"
    url = "https://googlecloudplatform.github.io/kubeflow-gke-docs/v1.5/docs"
  [[params.versions]]
    version = "v1.4"
    githubbranch = "v1.4-release"
    url = "https://googlecloudplatform.github.io/kubeflow-gke-docs/v1.4/docs"
  [[params.versions]]
    version = "dev"
    githubbranch = "main"
    url = "https://googlecloudplatform.github.io/kubeflow-gke-docs/dev/docs"

  # User interface configuration
  [params.ui]
    # Set menu navbar to be foldable
    sidebar_menu_foldable = true
    #  Set to true to disable breadcrumb navigation.
    breadcrumb_disable = false
    # Set to true to disable the About link in the site footer
    footer_about_disable = false
    # Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top navbar
    navbar_logo = true
    # Set to true if you don't want the top navbar to be translucent when over a `block/cover`, like on the homepage.
    navbar_translucent_over_cover_disable = false
    # Enable to show the side bar menu in its compact state.
    sidebar_menu_compact = false
    # Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
    sidebar_search_disable = false

      # Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
      # This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
      # If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
      # add "hide_feedback: true" to the page's front matter.
      [params.ui.feedback]
        enable = true
        # The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
        yes = 'Thank you! <a href="https://github.com/googlecloudplatform/kubeflow-gke-docs/issues/new">Send your feedback to us</a>.'
        no = 'Sorry to hear that. Please <a href="https://github.com/googlecloudplatform/kubeflow-gke-docs/issues/new">tell us how we can improve</a>.'

      # Adds a reading time to the top of each doc.
      # If you want this feature, but occasionally need to remove the Reading time from a single page, 
      # add "hide_readingtime: true" to the page's front matter
      [params.ui.readingtime]
        enable = true

  [params.links]
    # End user relevant links. These will show up on left side of footer and in the community page if you have one.
    [[params.links.user]]
      name = "Kubeflow mailing list"
      url = "https://www.kubeflow.org/docs/about/community/#kubeflow-mailing-list"
      icon = "fa fa-envelope"
      desc = "Discussion and help from Kubeflow users"
    [[params.links.user]]
      name = "Slack"
      url = "https://www.kubeflow.org/docs/about/community/#kubeflow-slack"
      icon = "fab fa-slack"
      desc = "Chat with Kubeflow users and developers"
    [[params.links.user]]
      name ="Twitter"
      url = "https://twitter.com/kubeflow"
      icon = "fab fa-twitter"
      desc = "Follow Kubeflow on Twitter"
    [[params.links.user]]
      name = "Stack Overflow"
      url = "https://stackoverflow.com/questions/tagged/kubeflow"
      icon = "fab fa-stack-overflow"
      desc = "Practical questions and answers for Kubeflow users"
    # Developer relevant links. These will show up on right side of footer and in the community page if you have one.
    [[params.links.developer]]
      name = "GitHub"
      url = "https://github.com/googlecloudplatform/kubeflow-distribution"
      icon = "fab fa-github"
      desc = "Kubeflow on Google Cloud repo"
    [[params.links.developer]]
      name = "Kubeflow community calendar"
      url = "https://www.kubeflow.org/docs/about/community/#kubeflow-community-calendars"
      icon = "fa fa-calendar"
      desc = "Upcoming community calls"
